### ISSUE TITLE
[vscode] [slack] "Select snooze duration for Slack"

### ISSUE THREAD

**Issue by jacksteamdev** [vsls-contrib/chat#395]
I've been seeing a quick pick with the message "Select snooze duration for Slack" popping up randomly on VSCode today.

Anyone know what this is and how I can make it stop? Is there a keybinding I don't know about?

![Snooze](https://user-images.githubusercontent.com/23390212/59460484-cd6c5680-8de4-11e9-8f00-98aa8a47cf78.png)

I don't really want to snooze Slack... 😞 

Awesome extension, btw. Love being able to easily invite people to LiveShare sessions via Slack!

https://github.com/karigari/vscode-chat/blob/26d9d0e93a7fae90033424af1e43d07a0978b02d/src/extension.ts#L388-L412

**Comment by arjun27** [comment]
Thanks for reporting this @jacksteamdev - this does look fishy, and might be also related to #379. Will get to you after further investigation.

**Comment by arjun27** [comment]
@jacksteamdev  - I have released 0.15.5 to the marketplace with a potential fix. My sense is that this was caused due to presence changes in the Live Share integration, and I have temporarily disabled them for now. Can you check if this fixes things for you? If so, I will release a better version that fixes the functionality and this issue together.

**Comment by jacksteamdev** [comment]
Hey @arjun27 - I just started a Live Share session and it works! Thanks for the temporary fix 🎉

**Comment by arjun27** [comment]
Marking this as resolved.
